docs: Add some doc to contribute to the project
osm-ui/react pull request #44
Opened 2018-04-01 18:30 UTC by GuillaumeAmat

2018-04-01 18:33 UTC, bleucitron requested changes

2018-04-01 18:33 UTC, iOiurson commented on CONTRIBUTING.md
> +`npm version` tests the code and build it. Then it upgrades the package version number according to the used keyword (patch, minor or major) and commit the modifications in Git (with a proper version
"tests the code and build**s** it"
"and commit**s**"

:p

2018-04-01 18:34 UTC, iOiurson commented on CONTRIBUTING.md
> +`npm version` tests the code and build it. Then it upgrades the package version number according to the used keyword (patch, minor or major) and commit the modifications in Git (with a proper version
I'm a bitch, I know

2018-04-01 23:23 UTC, GuillaumeAmat commented on CONTRIBUTING.md
> +`npm version` tests the code and build it. Then it upgrades the package version number according to the used keyword (patch, minor or major) and commit the modifications in Git (with a proper version
^^ It is fixed

2018-04-02 08:11 UTC, bleucitron approved these changes

2018-04-02 08:12 UTC, iOiurson commented
Ok !
I see that you `git pull develop`, leading to a 'Merge' commit.
In the future we should avoid it, and `rebase` instead, to keep the repo clean.

2018-04-02 08:12 UTC, merged